package com.amazonaws.ddbmapperdemo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMarshalling;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="UsersTable")
public class Users {
	
	private String id;
	private String name;
	private String status;
	private Set<String> friends;
	private Date joinDate = new Date();
	private PhoneNumber phone;
	
	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "Name")
	public String getName() {
		return name;
	}

	
	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute(attributeName = "Status")
	public String getStatus() {
		return status;
	}

	
	public void setStatus(String status) {
		this.status = status;
	}

	@DynamoDBAttribute(attributeName = "Friends")
	public Set<String> getFriends() {
		return friends;
	}


	public void setFriends(Set<String> friends) {
		this.friends = friends;
	}

	@DynamoDBAttribute(attributeName = "JoinDate")
	public Date getJoinDate() {
		return joinDate;
	}


	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}
	
	@DynamoDBAttribute(attributeName = "PhoneNumber")
	@DynamoDBMarshalling (marshallerClass = PhoneNumberMarshaller.class)
	public PhoneNumber getPhone() {
		return phone;
	}


	public void setPhone(PhoneNumber phone) {
		this.phone = phone;
	}


	public static void main(String[] args) throws InterruptedException {
		AWSResources.createTable();
		DynamoDBMapper dbMapper = new DynamoDBMapper(AWSResources.dbClient);
		Users users = new Users();
		
		users.setName("Snehangshu Karmakar");
		users.setStatus("Valid");
		Set<String> friends = new HashSet<String>();
		friends.add("Amit");
		friends.add("Ankur");
		friends.add("Ashish");
		users.setFriends(friends);
		
		Date d=new Date(System.currentTimeMillis());
		users.setJoinDate(d);
		
		PhoneNumber phone = new PhoneNumber();
		phone.setCountryCode("+91");
		phone.setAreaCode("120");
		phone.setPhoneNumber("8860841841");
		
		users.setPhone(phone);
		
		dbMapper.save(users);
		System.out.println("Saved user:"+"\n" + users.getId() + "\t" + users.getName() + "\t" + users.getStatus() + "\t" + users.getFriends() + "\t" + "("+users.getPhone().getCountryCode()
				+") "+users.getPhone().getAreaCode() + "-" + users.getPhone().getPhoneNumber());
		
		Users newUsers = dbMapper.load(Users.class, users.getId());
		System.out.println("Loaded user:"+"\n" + newUsers.getId() + "\t" + newUsers.getName() + "\t" + newUsers.getStatus() + "\t" + newUsers.getFriends() + "\t" + "("+newUsers.getPhone().getCountryCode()
				+") "+newUsers.getPhone().getAreaCode() + "-" + newUsers.getPhone().getPhoneNumber());
	}

}
